# Project-wide Gradle settings.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the Gradle Daemon.
# Setting a larger heap size helps with OutOfMemory errors during build.
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# Use AndroidX for libraries
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

API_BASE_URL=https://hermoso-rx6j.vercel.app/api/
