included:
  - Hermoso

disabled_rules:
  - todo
  - line_length

opt_in_rules:
  - empty_count
  - closure_spacing
  - redundant_nil_coalescing

identifier_name:
  min_length: 2
  excluded:
    - id
    - to
