export const mockCategories = [
  'Hair',
  'Skin',
  'Nails',
  'Makeup',
  'Massage',
  'Threading',
  'Waxing',
  'Bridal',
  'Kids',
  'Men Grooming',
  'Facial',
  'Body Treatment',
  'Hair Coloring',
  'Extensions',
  'Tattoo'
];

export const mockSalonNames = [
  'Glow Studio',
  'Beauty Haven',
  'Radiance Salon',
  'Elegance Spa',
  'Luxe Beauty',
  'Serene Salon',
  'Glam Central',
  'Beauty Bliss',
  'Crown Beauty',
  'Stellar Salon',
  'Pristine Salon',
  'Divine Beauty',
  'Chic Salon',
  'Opulent Spa',
  'Royal Beauty',
  'Stellar Spa',
  'Glamour Palace',
  'Beauty Oasis',
  'Shine Studio',
  'Elite Salon',
  'Aura Beauty',
  'Spa Sanctuary',
  'Phoenix Beauty',
  'Golden Salon',
  'Pearl Beauty',
  'Crystal Spa',
  'Essence Salon',
  'Harmony Beauty',
  'Bliss Salon',
  'Vision Beauty',
  'Dream Salon',
  'Infinity Spa',
  'Zenith Beauty',
  'Aesthetic Salon',
  'Artistry Beauty',
  'Boutique Salon',
  'Celebrity Spa',
  'Diamond Beauty',
  'Euphoria Salon',
  'Flawless Beauty',
  'Grace Salon',
  'Heaven Spa',
  'Iconic Beauty',
  'Jewel Salon',
  'Kingdom Beauty',
  'Luminous Spa',
  'Magic Salon',
  'Noble Beauty',
  'Oasis Spa',
  'Premier Salon',
  'Quest Beauty',
  'Regal Salon',
  'Splendor Spa',
  'Trinity Beauty',
  'Universe Salon',
  'Vogue Beauty',
  'Wonder Spa',
  'Xtreme Salon',
  'Youthful Beauty',
  'Zenith Salon',
  'Aurora Beauty',
  'Brilliant Spa',
  'Celestial Salon',
  'Deluxe Beauty',
  'Eternal Spa',
  'Fabulous Salon',
  'Gorgeous Beauty',
  'Heavenly Spa',
  'Immaculate Salon',
  'Jasmine Beauty',
  'Kaleidoscope Spa',
  'Luxurious Salon',
  'Majestic Beauty',
  'Noble Spa',
  'Opulent Salon',
  'Perfect Beauty',
  'Quintessential Spa',
  'Radiant Salon',
  'Sublime Beauty',
  'Timeless Spa',
  'Ultra Salon',
  'Velvet Beauty',
  'Wonderful Spa',
  'Xquisite Salon',
  'Youthful Spa',
  'Zest Beauty',
  'Amaranthine Salon',
  'Breathtaking Beauty',
  'Captivating Spa',
  'Dazzling Salon',
  'Exquisite Beauty',
  'Fabulous Spa',
  'Graceful Salon',
  'Harmonious Beauty',
  'Inspiring Spa',
  'Jazzy Salon',
  'Kinetic Beauty',
  'Lavish Spa',
  'Magnificent Salon',
  'Nurturing Beauty',
  'Ornamental Spa',
  'Phenomenal Salon',
  'Quintessential Beauty'
];

export const mockCities = [
  'Karachi',
  'Lahore',
  'Islamabad',
  'Rawalpindi',
  'Faisalabad',
  'Multan',
  'Hyderabad',
  'Peshawar',
  'Quetta',
  'Sialkot',
  'Gujranwala',
  'Sargodha',
  'Bahawalpur',
  'Sukkur',
  'Mirpur Khas',
  'Chitral',
  'Abbottabad',
  'Mingora',
  'Mardan',
  'Sheikhupura'
];

export const mockAddresses = [
  'Main Boulevard, {city}',
  'Downtown Plaza, {city}',
  'Shopping District, {city}',
  'Commercial Avenue, {city}',
  'Prime Location, {city}',
  'Business Hub, {city}',
  'Market Street, {city}',
  'Central Zone, {city}',
  'Elite Area, {city}',
  'Premium Zone, {city}',
  'Fashion Street, {city}',
  'Beauty Lane, {city}',
  'Wellness Park, {city}',
  'Grand Plaza, {city}',
  'Royal Courts, {city}',
  'Star Complex, {city}',
  'Vista Heights, {city}',
  'Sunset Boulevard, {city}',
  'Harbor View, {city}',
  'Park Avenue, {city}'
];

export const mockPhoneNumbers = [
  '+92-300-1234567',
  '+92-300-2345678',
  '+92-300-3456789',
  '+92-300-4567890',
  '+92-300-5678901',
  '+92-300-6789012',
  '+92-300-7890123',
  '+92-300-8901234',
  '+92-300-9012345',
  '+92-321-1234567',
  '+92-321-2345678',
  '+92-321-3456789',
  '+92-321-4567890',
  '+92-321-5678901',
  '+92-321-6789012',
  '+92-321-7890123',
  '+92-321-8901234',
  '+92-321-9012345',
  '+92-333-1234567',
  '+92-333-2345678'
];

export const mockOwnerNames = [
  'Ayesha Khan',
  'Fatima Ahmed',
  'Hira Ali',
  'Amina Hassan',
  'Zainab Malik',
  'Nida Hussain',
  'Rabia Rauf',
  'Saira Amin',
  'Urooj Mirza',
  'Yasmin Khan',
  'Bushra Iftikhar',
  'Dina Farooq',
  'Iqra Nadeem',
  'Jameela Siddiqui',
  'Khadija Riaz',
  'Layla Nasir',
  'Mahira Baig',
  'Nimra Adil',
  'Osman Malik',
  'Parveen Safdar',
  'Qurat ul Ain',
  'Rukhsana Malik',
  'Salma Farooq',
  'Tahira Khan',
  'Ummara Iqbal',
  'Vina Ahmed',
  'Waheeda Amin',
  'Xenia Rauf',
  'Yasira Hassan',
  'Zara Malik',
  'Amelia Khan',
  'Bilquis Ahmed',
  'Chanda Ali',
  'Deena Hassan',
  'Esha Malik',
  'Farida Hussain',
  'Gulnar Rauf',
  'Hanna Amin',
  'Inaya Mirza',
  'Jihan Khan',
  'Kaida Iftikhar',
  'Lina Farooq',
  'Mariam Nadeem',
  'Nadia Siddiqui',
  'Olivia Riaz',
  'Priya Nasir',
  'Qudsiya Baig',
  'Rania Adil',
  'Sophia Malik',
  'Tamanna Safdar'
];

export const mockStaffNames = [
  'Maira Khan',
  'Saba Ali',
  'Noor Ahmed',
  'Aliza Malik',
  'Bushra Hassan',
  'Chanda Hussain',
  'Dina Rauf',
  'Erum Amin',
  'Farzana Mirza',
  'Gina Khan',
  'Hina Iftikhar',
  'Iqra Farooq',
  'Javeria Nadeem',
  'Kamila Siddiqui',
  'Layla Riaz',
  'Mina Nasir',
  'Nadia Baig',
  'Oman Adil',
  'Pakiza Malik',
  'Qadira Safdar',
  'Rania Khan',
  'Samina Ahmed',
  'Tahira Ali',
  'Uma Hassan',
  'Vina Malik',
  'Wafa Hussain',
  'Xenia Rauf',
  'Yasmin Amin',
  'Zainab Mirza',
  'Aisha Khan',
  'Bina Iftikhar',
  'Carla Farooq',
  'Dalia Nadeem',
  'Erin Siddiqui',
  'Farrah Riaz',
  'Gaya Nasir',
  'Hira Baig',
  'Iris Adil',
  'Jameela Malik',
  'Kayla Safdar',
  'Lena Khan',
  'Mona Ahmed',
  'Nisha Ali',
  'Oven Hassan',
  'Piya Malik',
  'Queenie Hussain',
  'Raya Rauf',
  'Samara Amin',
  'Talia Mirza',
  'Usha Khan'
];

export const mockServiceNames = [
  // Hair Services
  'Hair Cut',
  'Hair Styling',
  'Hair Coloring',
  'Highlights',
  'Hair Smoothing',
  'Hair Extensions',
  'Blow Dry',
  'Perming',
  'Hair Treatment',
  'Scalp Treatment',

  // Skin Services
  'Facial',
  'Deep Cleansing Facial',
  'Hydrating Facial',
  'Anti-Aging Facial',
  'Acne Treatment',
  'Chemical Peel',
  'Microdermabrasion',
  'Skin Whitening',
  'Skin Rejuvenation',
  'Sensitive Skin Treatment',

  // Nail Services
  'Manicure',
  'Pedicure',
  'Gel Nails',
  'Nail Art',
  'Acrylic Nails',
  'French Manicure',
  'Nail Extension',
  'Nail Repair',
  'Nail Polish',
  'Nail Spa',

  // Makeup Services
  'Bridal Makeup',
  'Party Makeup',
  'Professional Makeup',
  'Eye Makeup',
  'Eyebrow Threading',
  'Eyelash Extensions',
  'Makeup Lesson',
  'HD Makeup',
  'Airbrush Makeup',
  'Special Effects Makeup',

  // Massage Services
  'Full Body Massage',
  'Head Massage',
  'Back Massage',
  'Swedish Massage',
  'Thai Massage',
  'Deep Tissue Massage',
  'Aromatherapy Massage',
  'Hot Stone Massage',
  'Reflexology',
  'Foot Massage',

  // Threading & Waxing
  'Eyebrow Threading',
  'Upper Lip Threading',
  'Full Face Threading',
  'Body Waxing',
  'Leg Waxing',
  'Arm Waxing',
  'Brazilian Waxing',
  'Bikini Waxing',
  'Face Waxing',
  'Threading & Tinting',

  // Bridal Services
  'Bridal Package',
  'Pre-Wedding Glow',
  'Bridal Skincare',
  'Bridal Hair',
  'Bridal Nails',
  'Henna Application',
  'Bridal Massage',
  'Complete Bridal Makeover',
  'Wedding Day Touch-up',
  'Groom Grooming',

  // Men Grooming
  'Beard Trim',
  'Men Haircut',
  'Shaving Service',
  'Men Facial',
  'Men Massage',
  'Grooming Package',
  'Beard Styling',
  'Hair Straightening',
  'Eyebrow Shaping',
  'Men Body Waxing'
];

export const mockServiceDescriptions = [
  'Professional and quality service',
  'Premium quality treatment',
  'Expert service by trained professionals',
  'Luxurious experience',
  'Personalized care',
  'State-of-the-art service',
  'Customized treatment',
  'Relaxing and rejuvenating',
  'High-quality materials used',
  'Experienced staff',
  'Satisfying results',
  'Best in class service',
  'Professional expertise',
  'Premium finishing',
  'Complete care package',
  'Therapeutic benefits',
  'Transformative treatment',
  'Stress relief service',
  'Beauty enhancement',
  'Wellness focused'
];

export const mockDesignations = [
  'Stylist',
  'Beauty Therapist',
  'Nail Artist',
  'Makeup Artist',
  'Masseur',
  'Hair Specialist',
  'Skin Specialist',
  'Senior Stylist',
  'Lead Therapist',
  'Junior Stylist',
  'Assistant',
  'Receptionist',
  'Manager',
  'Supervisor',
  'Technician'
];

export const mockWorkingDays = [
  ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
  ['tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
  ['monday', 'wednesday', 'thursday', 'friday', 'saturday'],
  ['monday', 'tuesday', 'wednesday', 'friday', 'saturday'],
  ['monday', 'tuesday', 'thursday', 'friday', 'saturday'],
  ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
  ['tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
  ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'sunday'],
  ['wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
  ['thursday', 'friday', 'saturday', 'sunday', 'monday']
];

export const mockShiftTimes = [
  { start: '09:00', end: '17:00' },
  { start: '10:00', end: '18:00' },
  { start: '08:00', end: '16:00' },
  { start: '11:00', end: '19:00' },
  { start: '09:30', end: '17:30' },
  { start: '10:30', end: '18:30' },
  { start: '08:30', end: '16:30' },
  { start: '09:00', end: '18:00' },
  { start: '10:00', end: '19:00' },
  { start: '08:00', end: '17:00' }
];

export const mockSalaryTypes = ['monthly', 'weekly', 'daily', 'hourly'];

export const mockCustomerNames = [
  'Sara Ahmed',
  'Hina Khan',
  'Amina Hassan',
  'Aaiza Malik',
  'Nida Hussain',
  'Rabia Rauf',
  'Dina Farooq',
  'Iqra Nadeem',
  'Jameela Siddiqui',
  'Khadija Riaz',
  'Layla Nasir',
  'Mahira Baig',
  'Nimra Adil',
  'Parveen Safdar',
  'Qurat ul Ain',
  'Rukhsana Malik',
  'Salma Farooq',
  'Tahira Khan',
  'Ummara Iqbal',
  'Vina Ahmed',
  'Waheeda Amin',
  'Yasira Hassan',
  'Zara Malik',
  'Amelia Khan',
  'Bilquis Ahmed',
  'Chanda Ali',
  'Deena Hassan',
  'Esha Malik',
  'Farida Hussain',
  'Gulnar Rauf',
  'Hanna Amin',
  'Inaya Mirza',
  'Jihan Khan',
  'Kaida Iftikhar',
  'Lina Farooq',
  'Mariam Nadeem',
  'Nadia Siddiqui',
  'Olivia Riaz',
  'Priya Nasir',
  'Qudsiya Baig',
  'Rania Adil',
  'Sophia Malik',
  'Tamanna Safdar',
  'Usman Ahmed',
  'Vikram Hassan',
  'Waleed Malik',
  'Xenophon Hussain',
  'Yasir Rauf',
  'Zamir Amin',
  'Ahmed Khan'
];

export const mockReviewComments = [
  'Excellent service and professional staff',
  'Very satisfied with the treatment',
  'Great atmosphere and friendly staff',
  'Highly recommended',
  'Outstanding experience',
  'Best salon in town',
  'Will definitely come back',
  'Amazing results',
  'Professional and courteous',
  'Worth every penny',
  'Top quality service',
  'Staff is very skilled',
  'Clean and hygienic',
  'Great value for money',
  'Exceeded my expectations',
  'Wonderful experience',
  'Staff made me feel comfortable',
  'Precise and careful work',
  'Very satisfied overall',
  'Would recommend to friends'
];

export const mockSalonDescriptions = [
  'Premium beauty salon offering complete beauty solutions',
  'A perfect destination for your beauty needs',
  'Luxury salon with expert stylists',
  'Your one-stop shop for all beauty services',
  'Professional salon with latest techniques',
  'Relax and rejuvenate at our beauty haven',
  'Experience luxury beauty treatments',
  'Expert care for your beauty needs',
  'State-of-the-art salon with experienced team',
  'Transform your look with our expert services',
  'Premium services for the modern woman',
  'Beauty and wellness sanctuary',
  'Professional beauty solutions',
  'Your beauty destination',
  'Expert salon services at affordable prices',
  'Quality beauty treatments guaranteed',
  'Professional team dedicated to your beauty',
  'Transformative beauty experiences',
  'Your trusted beauty partner',
  'Excellence in beauty services'
];

export const mockWorkingHours = {
  monday: { open: '09:00', close: '19:00', off: false },
  tuesday: { open: '09:00', close: '19:00', off: false },
  wednesday: { open: '09:00', close: '19:00', off: false },
  thursday: { open: '09:00', close: '19:00', off: false },
  friday: { open: '10:00', close: '20:00', off: false },
  saturday: { open: '10:00', close: '20:00', off: false },
  sunday: { open: '12:00', close: '18:00', off: false }
};

export const mockServicePrices = [15, 20, 25, 30, 35, 40, 45, 50, 60, 75, 85, 100, 120, 150, 200];

export const mockServiceDurations = [30, 45, 60, 75, 90, 120, 150, 180];

export const mockCommissionRates = [8, 10, 12, 15, 18, 20];

export const mockEventNames = [
  'Bridal Complete Package',
  'Premium Bridal Experience',
  'Royal Wedding Package',
  'Birthday Celebration Package',
  'Party Glam Package',
  'Eid Special Package',
  'Independence Day Special',
  'Corporate Event Package',
  'Anniversary Package',
  'Engagement Ceremony Package',
  'Pre-Wedding Glow Package',
  'Mehendi Function Package',
  'Valima Package',
  'Sweet Sixteen Package',
  'New Year Party Package',
  'Graduation Party Package',
  'Formal Event Package',
  'Festival Special Package',
  'Summer Glow Package',
  'Winter Care Package'
];

export const mockEventDescriptions = [
  'Complete beauty transformation for your special day',
  'Premium package with all essential services',
  'Luxury treatment package for memorable occasions',
  'All-inclusive beauty solution',
  'Perfect package for your celebration',
  'Comprehensive beauty services bundle',
  'Special occasion complete package',
  'Transform your look with our exclusive package',
  'Everything you need in one package',
  'Ultimate beauty experience',
  'Curated services for your event',
  'Professional styling package',
  'Complete makeover solution',
  'Premium beauty bundle',
  'Exclusive event package',
  'Full-service beauty treatment',
  'Celebration ready package',
  'Special day complete care',
  'All-in-one beauty solution',
  'Custom event package'
];

export const mockEventCategories = [
  'bridal',
  'party',
  'eid',
  'independence_day',
  'birthday',
  'engagement',
  'anniversary',
  'corporate',
  'wedding',
  'other'
];
